name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: 1.2.21
        
    - name: Install dependencies
      run: bun install
      
    - name: Debug environment
      run: |
        echo "Bun version: $(bun --version)"
        echo "Node version: $(node --version)"
        echo "TypeScript version: $(bunx tsc --version)"
        echo "vue-tsc version: $(bunx vue-tsc --version)"
        
    - name: Type check only
      run: bun run type-check
      
    - name: Build
      run: bun run build
      
    - name: Copy coded files to dist
      run: |
        cp coded*.txt dist/ || echo "No coded*.txt files found"
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        cname: atom.yusong.moe
